### ISSUE TITLE
Failed to set ntp: NTP not supported

### ISSUE THREAD

**Issue by LogoJK** [Sinusbot/installer-linux#92] opened 2022-08-01 16:34 UTC
`Command which failed was: "      timedatectl set-ntp yes". Please try to execute it manually and attach the output to the bug report in the forum thread.
If it still doesn't work report this to the author at https://forum.sinusbot.com/threads/sinusbot-installer-script.1200/ only. Not a PN or a bad review, cause this is an error of your system not of the installer script. Line 682.`

Please Help. 
Thank you very much if you actually do help.

**Comment by t4ba** [comment] 2022-09-07 05:56
same here

**Comment by mxschmitt** [comment] 2022-09-29 14:01
Dupe of https://github.com/SinusBot/installer-linux/issues/91.

**Closed as not planned by mxschmitt** 2022-09-29 14:01 UTC
